
package Frames;

import Clases.Cliente;
import java.sql.*;
import javax.swing.JOptionPane;

public class FrameCliente extends javax.swing.JFrame {

   Cliente cliente = new Cliente();
   
    
    public FrameCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        t1.setVisible(false);
        t2.setVisible(false);
        nombrebox.setVisible(false);
        contactobox.setVisible(false);
        Eliminar.setVisible(false);
        GuardarCambios.setVisible(false);
        GuardarCliente.setVisible(false);
        Habilitar.setVisible(false);
        Buscar2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        idt = new javax.swing.JLabel();
        idbox = new javax.swing.JTextField();
        t1 = new javax.swing.JLabel();
        contactobox = new javax.swing.JTextField();
        t2 = new javax.swing.JLabel();
        nombrebox = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        GuardarCambios = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Habilitar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Nuevo = new javax.swing.JButton();
        GuardarCliente = new javax.swing.JButton();
        Buscar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Clientes");

        idt.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        idt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idt.setText("ID Cliente:");

        idbox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        idbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idboxActionPerformed(evt);
            }
        });
        idbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idboxKeyTyped(evt);
            }
        });

        t1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t1.setText("Contacto de Cliente:");

        contactobox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        contactobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactoboxActionPerformed(evt);
            }
        });
        contactobox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactoboxKeyTyped(evt);
            }
        });

        t2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        t2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t2.setText("Nombre de cliente:");

        nombrebox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nombrebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreboxActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        GuardarCambios.setText("Guardar");
        GuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCambiosActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Habilitar.setText("Habilitar Edicion");
        Habilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabilitarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        GuardarCliente.setText("Guardar");
        GuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarClienteActionPerformed(evt);
            }
        });

        Buscar2.setText("Buscar de nuevo");
        Buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contactobox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombrebox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idbox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buscar)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Buscar2)
                        .addGap(43, 43, 43)
                        .addComponent(GuardarCliente)
                        .addGap(78, 78, 78)
                        .addComponent(jButton1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Nuevo)
                        .addGap(37, 37, 37)
                        .addComponent(Eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(GuardarCambios)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Habilitar)
                        .addGap(122, 122, 122))))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idt)
                    .addComponent(idbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1)
                    .addComponent(contactobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2)
                    .addComponent(nombrebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarCambios)
                    .addComponent(Eliminar)
                    .addComponent(Nuevo))
                .addGap(18, 18, 18)
                .addComponent(Habilitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarCliente)
                    .addComponent(Buscar2)
                    .addComponent(jButton1))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idboxActionPerformed

    private void contactoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactoboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactoboxActionPerformed

    private void nombreboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreboxActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        int id = Integer.valueOf(idbox.getText().trim());
        
        String texto = idbox.getText().trim();
        
        if(texto.length() ==0){
            idbox.setText("");
            JOptionPane.showMessageDialog(null, "No se permiten campos vacios");
        }else{
            
            if(cliente.ValidarID(id)){
                try{
                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/dulceria","root","");
                    PreparedStatement select = cn.prepareStatement("select * from clientes where id = ?");

                    select.setInt(1, id);

                    ResultSet rs = select.executeQuery();

                    if(rs.next()){

                        t1.setVisible(true);
                        contactobox.setVisible(true);contactobox.setEditable(false);
                        t2.setVisible(true);
                        nombrebox.setVisible(true);nombrebox.setEditable(false);

                        Buscar.setVisible(false);
                        idbox.setEditable(false);
                        Habilitar.setVisible(true);
                        Buscar2.setVisible(true);
                        Nuevo.setVisible(false);

                        nombrebox.setText(rs.getString("nombre"));
                        contactobox.setText(rs.getString("telefono"));

                    }else{
                        JOptionPane.showMessageDialog(null, "Usuario no encontrado");
                    }

                }catch(Exception e){
                    System.err.print("Error: " + e);
                }

            }else{
                idbox.setText("");
            }
        }    

    }//GEN-LAST:event_BuscarActionPerformed

    private void GuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCambiosActionPerformed

        String nombre = nombrebox.getText().trim();
        String contacto = contactobox.getText().trim();
        int id = Integer.parseInt(idbox.getText().trim());
        
        if(nombre.length()==0 || contacto.length()==0){
            nombrebox.setText("");
            contactobox.setText("");
            JOptionPane.showMessageDialog(null, "No se permiten campos vacios");
        }else{
            cliente.Editar(id, nombre, contacto);
            idbox.setText("");
            nombrebox.setText("");
            contactobox.setText("");
            
            t1.setVisible(false);
            t2.setVisible(false);
            nombrebox.setVisible(false);
            contactobox.setVisible(false);
            Eliminar.setVisible(false);
            GuardarCambios.setVisible(false);
            Buscar2.setVisible(false);
            
            idbox.setEditable(true);
            Buscar.setVisible(true);
            Nuevo.setVisible(true);            
        }
        

        

    }//GEN-LAST:event_GuardarCambiosActionPerformed

    private void HabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabilitarActionPerformed
        
        GuardarCambios.setVisible(true);
        Nuevo.setVisible(false);
        Eliminar.setVisible(true);
        nombrebox.setEditable(true);
        contactobox.setEditable(true);
        Habilitar.setVisible(false);
    }//GEN-LAST:event_HabilitarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrameMenu ir = new FrameMenu();
        ir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        
        int id = Integer.parseInt(idbox.getText().trim());
        cliente.Eliminar(id);
        
        idbox.setText("");
        nombrebox.setText("");
        contactobox.setText("");

        t1.setVisible(false);
        t2.setVisible(false);
        nombrebox.setVisible(false);
        contactobox.setVisible(false);
        Eliminar.setVisible(false);
        GuardarCambios.setVisible(false);
        Buscar2.setVisible(false);

        idbox.setEditable(true);
        Buscar.setVisible(true);
        Nuevo.setVisible(true);           
        
    }//GEN-LAST:event_EliminarActionPerformed

    private void GuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarClienteActionPerformed
        String nombre = nombrebox.getText().trim();
        String contacto = contactobox.getText().trim();
        
        if(nombre.length()==0 || contacto.length()==0){
            nombrebox.setText("");
            contactobox.setText("");
            JOptionPane.showMessageDialog(null, "No se permiten campos vacios");
        }else{
            cliente.NuevoCliente(nombre, contacto);
            JOptionPane.showMessageDialog(null, "El registro ha sido agregado");
            nombrebox.setText("");
            contactobox.setText("");

            t1.setVisible(false);
            t2.setVisible(false);
            nombrebox.setVisible(false);
            contactobox.setVisible(false);
            Eliminar.setVisible(false);
            GuardarCambios.setVisible(false);
            GuardarCliente.setVisible(false);
            Habilitar.setVisible(false);
            Buscar2.setVisible(false);

            Buscar.setVisible(true);
            Nuevo.setVisible(true);
            idt.setVisible(true);
            idbox.setVisible(true);
            idbox.setText("");
        }
    }//GEN-LAST:event_GuardarClienteActionPerformed

    private void Buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar2ActionPerformed
        t1.setVisible(false);
        t2.setVisible(false);
        nombrebox.setVisible(false);
        contactobox.setVisible(false);
        Eliminar.setVisible(false);
        GuardarCambios.setVisible(false);
        GuardarCambios.setVisible(false);
        GuardarCliente.setVisible(false);
        Habilitar.setVisible(false);
        Buscar.setVisible(true);
        Nuevo.setVisible(true);
        Buscar2.setVisible(false);
        
        idbox.setText("");
        idbox.setEditable(true);
        nombrebox.setText("");
        contactobox.setText("");
 
    }//GEN-LAST:event_Buscar2ActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        
        idt.setVisible(false);
        idbox.setVisible(false);
        Buscar.setVisible(false);
        GuardarCambios.setVisible(false);
        Eliminar.setVisible(false);
        Habilitar.setVisible(false);
        Nuevo.setVisible(false);
        Buscar2.setVisible(false);   
        
        GuardarCliente.setVisible(true);
        t1.setVisible(true);
        t2.setVisible(true);
        nombrebox.setVisible(true);
        nombrebox.setText("");nombrebox.setEditable(true);
        contactobox.setVisible(true);
        contactobox.setText("");contactobox.setEditable(true);
        
    }//GEN-LAST:event_NuevoActionPerformed

    private void idboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idboxKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane,"Solo se pueden ingresar valores numericos");
        }
    }//GEN-LAST:event_idboxKeyTyped

    private void contactoboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactoboxKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane,"Solo se pueden ingresar valores numericos");
        }
    }//GEN-LAST:event_contactoboxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Buscar2;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton GuardarCambios;
    private javax.swing.JButton GuardarCliente;
    private javax.swing.JButton Habilitar;
    private javax.swing.JButton Nuevo;
    private javax.swing.JTextField contactobox;
    private javax.swing.JTextField idbox;
    private javax.swing.JLabel idt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombrebox;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    // End of variables declaration//GEN-END:variables
}
