
package Frames;

import Clases.Producto;
import Clases.Venta;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class FrameVenta extends javax.swing.JFrame {

    Producto pc = new Producto();
    Venta vta = new Venta();
    float total;
    float precio;
    String cliente;
    boolean v1 = false;
    boolean v2 = false;
    String Texto;
    
    public FrameVenta() {
        initComponents();
        this.setLocationRelativeTo(null); 
        
        this.claves.setModel(pc.modeloproductos());
        Lista.setText(vta.timeStamp);
        
        Lista.setEditable(false);
        nombret.setVisible(false);
        nombrebox.setVisible(false);
        Confirmar.setVisible(false);
        GuardarCliente.setVisible(false);
        contact.setVisible(false);
        contactobox.setVisible(false);
        validar2.setVisible(false);
        totalbox.setEditable(false);
        
        //LIMPIEZA DE INICIALIZACION
        clavebox.setText("");
        cantbox.setText("");
        contactobox.setText("");
        nombrebox.setText("");
        Lista.setText(null);
        total = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        claves = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        clavebox = new javax.swing.JTextField();
        cantbox = new javax.swing.JTextField();
        cant = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Confirmar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        contactobox = new javax.swing.JTextField();
        nombret = new javax.swing.JLabel();
        nombrebox = new javax.swing.JTextField();
        Nuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JTextArea();
        Validar = new javax.swing.JButton();
        GuardarCliente = new javax.swing.JButton();
        idt = new javax.swing.JLabel();
        idbox = new javax.swing.JTextField();
        validar2 = new javax.swing.JButton();
        totalbox = new javax.swing.JTextField();
        nombret1 = new javax.swing.JLabel();
        conbox = new javax.swing.JTextField();
        CON = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        claves.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REALIZAR VENTA");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Clave producto:");

        clavebox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        clavebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveboxActionPerformed(evt);
            }
        });
        clavebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                claveboxKeyTyped(evt);
            }
        });

        cantbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantboxKeyTyped(evt);
            }
        });

        cant.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cant.setText("Cantidad:");

        Agregar.setText("Agregar a la venta");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Volver y Cancelar Venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Lista de Productos");

        contact.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contact.setText("Contacto de Cliente:");

        contactobox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        contactobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactoboxActionPerformed(evt);
            }
        });
        contactobox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactoboxKeyTyped(evt);
            }
        });

        nombret.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        nombret.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombret.setText("Nombre de cliente:");

        nombrebox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nombrebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreboxActionPerformed(evt);
            }
        });

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        Lista.setColumns(20);
        Lista.setRows(5);
        jScrollPane1.setViewportView(Lista);

        Validar.setText("Validar");
        Validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidarActionPerformed(evt);
            }
        });

        GuardarCliente.setText("Guardar");
        GuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarClienteActionPerformed(evt);
            }
        });

        idt.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        idt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idt.setText("ID Cliente:");

        idbox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        idbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idboxActionPerformed(evt);
            }
        });
        idbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idboxKeyTyped(evt);
            }
        });

        validar2.setText("Volver a Validar");
        validar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validar2ActionPerformed(evt);
            }
        });

        totalbox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        totalbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalboxActionPerformed(evt);
            }
        });

        nombret1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        nombret1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombret1.setText("TOTAL: $");

        conbox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        conbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conboxActionPerformed(evt);
            }
        });
        conbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                conboxKeyTyped(evt);
            }
        });

        CON.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CON.setText("PAGAR CON: $");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(390, 390, 390))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(93, 93, 93))))
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(nombret1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalbox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(CON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conbox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(Confirmar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(claves, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(cant))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cantbox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(clavebox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(contact)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(contactobox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(idt)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(idbox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(validar2)
                                                    .addComponent(nombret))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nombrebox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(GuardarCliente, javax.swing.GroupLayout.Alignment.TRAILING))))
                                        .addGap(11, 11, 11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Agregar)
                                        .addGap(41, 41, 41))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Nuevo)
                        .addGap(68, 68, 68)
                        .addComponent(Validar)
                        .addGap(101, 101, 101)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(claves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(294, 294, 294)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clavebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cant)
                            .addComponent(cantbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(Agregar)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idt)
                            .addComponent(idbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contact)
                            .addComponent(contactobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nuevo)
                            .addComponent(Validar))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombret)
                            .addComponent(nombrebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GuardarCliente)
                            .addComponent(validar2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombret1)
                    .addComponent(totalbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CON)
                    .addComponent(conbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Confirmar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void claveboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveboxActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        
        int clave = Integer.parseInt(clavebox.getText().trim());
        int cantidad = Integer.parseInt(cantbox.getText().trim());
        
        String c1=clavebox.getText().trim();
        String c2=cantbox.getText().trim();
        
        if(c1.length()==0 ||c2.length()==0){
            JOptionPane.showMessageDialog(null, "Estos campos no pueden estar vacios");
            clavebox.setText(null);
            cantbox.setText(null);
        }else{
           
            if(vta.ValidadProducto(clave)){

                if(vta.ValidarEstado(clave)){
                   if(vta.ValidarCantidad(clave, cantidad)){
                       //CODIGO

                       int cant = vta.ObtenerCant(clave);

                       int cantnueva = cant - cantidad;
                       vta.ActualizarInventario(clave, cantnueva);

                       String producto = vta.Producto(clave);
                       float precio = vta.Precio(clave) * cantidad;
                       
                       v1 = true;

                       total = total + precio;
                       
                       totalbox.setText(Float.toString(total) );

                       Lista.append("\n" + producto + "  x" + cantidad + "  : $" + precio);

                       clavebox.setText(null);
                       cantbox.setText(null);

                    }else{
                        JOptionPane.showMessageDialog(null, "Cantidad Invalida");

                        cantbox.setText(null);
                    } 
                }
                else{
                    JOptionPane.showMessageDialog(null, "Producto no esta en venta");
                    clavebox.setText(null);
                    cantbox.setText(null);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Producto no encontrado");
                clavebox.setText(null);
                cantbox.setText(null);
            }

            Confirmar.setVisible(true);
        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
       
        //SI YA SE COMPRO MINIMO UN ARTICULO Y SE INGRESO UN CLIENTE, YA ES POSIBLE CONFIRMAR LA COMPRA
        if(v1 && v2){
            
            float ingreso = Float.parseFloat(conbox.getText().trim());
            
            if(ingreso > total){
                
                float devolucion = ingreso - total;
                
                int randomid;
                
                do{
                    randomid = (int) Math.floor(Math.random()*(5000-1000+1)+1000);
                    
                }while(!vta.ValidarClave(randomid));
                
                
                String clientecompra = nombrebox.getText().trim();
                
                Texto = ("CLAVE DE COMPRA: " + randomid + "\n" + vta.timeStamp + "\nCLIENTE: " + clientecompra + "\n" + Lista.getText().replace("\n", "\r\n") + "\n\n" + "TOTAL: $" + total + "\nPAGADO CON: $" + ingreso + "\nDEVOLUCION: $" + devolucion);
                
                Ticket ver = new Ticket();
                ver.setVisible(true);
                this.setVisible(false);
                ver.lista.setText(Texto);
                
            }else{
                JOptionPane.showMessageDialog(null, "El monto a pagar es mayor");
                conbox.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos y hacer minimo una compra");
        }
        
        
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void contactoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactoboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactoboxActionPerformed

    private void nombreboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreboxActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        
        Nuevo.setVisible(false);
        Validar.setVisible(false);
        idt.setVisible(false);
        idbox.setVisible(false);
        idbox.setText("");
        
        nombret.setVisible(true);
        nombrebox.setVisible(true);
        contact.setVisible(true);
        contactobox.setVisible(true);
        GuardarCliente.setVisible(true);
        validar2.setVisible(true);
    }//GEN-LAST:event_NuevoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrameMenu menu = new FrameMenu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarClienteActionPerformed
       
        String nombre = nombrebox.getText().trim();
        String contacto = contactobox.getText().trim();
        
        if(nombre.length()==0 || contacto.length()==0){
            JOptionPane.showMessageDialog(null, "Campos vacios");
            clavebox.setText(null);
            cantbox.setText(null);
        }else{
            vta.NuevoCliente(nombre, contacto);
            nombrebox.setEditable(false);
            contactobox.setEditable(false);
            
            v2 = true;
            
            cliente = nombrebox.getText();
            
            GuardarCliente.setVisible(false);
            validar2.setVisible(false);
        }
            
        
    }//GEN-LAST:event_GuardarClienteActionPerformed

    private void idboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idboxActionPerformed

    private void validar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validar2ActionPerformed
        
        nombret.setVisible(false);
        nombrebox.setVisible(false);
        Confirmar.setVisible(false);
        GuardarCliente.setVisible(false);
        contact.setVisible(false);
        contactobox.setVisible(false);
        validar2.setVisible(false);
        
        contactobox.setText("");
        nombrebox.setText("");
        
        idt.setVisible(true);
        idbox.setVisible(true);
        
        idbox.setText("");
        Validar.setVisible(true);
        Nuevo.setVisible(true);
        
    }//GEN-LAST:event_validar2ActionPerformed

    private void totalboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalboxActionPerformed

    private void conboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conboxActionPerformed

    private void ValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidarActionPerformed
        int id = Integer.valueOf(idbox.getText().trim());
        
        if(vta.ValidarID(id)){
            try{
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/dulceria","root","");
                PreparedStatement select = cn.prepareStatement("select * from clientes where id = ?");

                select.setInt(1, id);

                ResultSet rs = select.executeQuery();

                if(rs.next()){

                    contact.setVisible(true);  
                    contactobox.setVisible(true);contactobox.setEditable(false);
                    nombret.setVisible(true);
                    nombrebox.setVisible(true);nombrebox.setEditable(false);
                    
                    Nuevo.setVisible(false);
                    Validar.setVisible(false);
                    idbox.setEditable(false);
                    
                    v2 = true;

                    nombrebox.setText(rs.getString("nombre"));
                    cliente = nombrebox.getText();
                    contactobox.setText(rs.getString("telefono"));    

                }else{
                    JOptionPane.showMessageDialog(null, "Usuario no encontrado");
                }

            }catch(Exception e){
                System.err.print("Error: " + e);
            }
            
        }else{
            idbox.setText("");
        }
        
    }//GEN-LAST:event_ValidarActionPerformed

    private void claveboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_claveboxKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane,"Solo se pueden ingresar valores numericos");
        }
    }//GEN-LAST:event_claveboxKeyTyped

    private void cantboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantboxKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane,"Solo se pueden ingresar valores numericos");
        }
    }//GEN-LAST:event_cantboxKeyTyped

    private void idboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idboxKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane,"Solo se pueden ingresar valores numericos");
        }
    }//GEN-LAST:event_idboxKeyTyped

    private void contactoboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactoboxKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane,"Solo se pueden ingresar valores numericos");
        }
    }//GEN-LAST:event_contactoboxKeyTyped

    private void conboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conboxKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane,"Solo se pueden ingresar valores numericos");
        }
    }//GEN-LAST:event_conboxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JLabel CON;
    private javax.swing.JButton Confirmar;
    private javax.swing.JButton GuardarCliente;
    private javax.swing.JTextArea Lista;
    private javax.swing.JButton Nuevo;
    private javax.swing.JButton Validar;
    private javax.swing.JLabel cant;
    private javax.swing.JTextField cantbox;
    private javax.swing.JTextField clavebox;
    private javax.swing.JComboBox<String> claves;
    private javax.swing.JTextField conbox;
    private javax.swing.JLabel contact;
    private javax.swing.JTextField contactobox;
    private javax.swing.JTextField idbox;
    private javax.swing.JLabel idt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombrebox;
    private javax.swing.JLabel nombret;
    private javax.swing.JLabel nombret1;
    private javax.swing.JTextField totalbox;
    private javax.swing.JButton validar2;
    // End of variables declaration//GEN-END:variables
}
