
package Frames;

import Clases.Producto;
import java.sql.*;
import javax.swing.JOptionPane;

public class Inventario extends javax.swing.JFrame {

    Producto pc = new Producto();

    
    public Inventario() {
        initComponents();
        this.setLocationRelativeTo(null); 
        
        this.claves.setModel(pc.modeloproductos());
        claves.setEditable(false);
        Eliminar.setVisible(false);
        nombret.setVisible(false);
        nombrebox.setVisible(false); nombrebox.setEditable(false);
        preciot.setVisible(false);
        preciobox.setVisible(false); preciobox.setEditable(false);
        estadot.setVisible(false);
        estbox.setVisible(false); estbox.setEditable(false);
        Habilitar.setVisible(false);
        Guardar.setVisible(false);
        cant.setVisible(false);
        cantbox.setVisible(false);cantbox.setEditable(false);
        Buscar2.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        preciobox = new javax.swing.JTextField();
        nombret = new javax.swing.JLabel();
        preciot = new javax.swing.JLabel();
        nombrebox = new javax.swing.JTextField();
        clavebox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        Habilitar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        estbox = new javax.swing.JTextField();
        estadot = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Buscar2 = new javax.swing.JButton();
        cant = new javax.swing.JLabel();
        cantbox = new javax.swing.JTextField();
        claves = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        preciobox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        preciobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioboxActionPerformed(evt);
            }
        });
        preciobox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioboxKeyTyped(evt);
            }
        });

        nombret.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        nombret.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombret.setText("Nombre:");

        preciot.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        preciot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preciot.setText("Precio:");

        clavebox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        clavebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveboxActionPerformed(evt);
            }
        });
        clavebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                claveboxKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Producto ");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Habilitar.setText("Habilitar Edicion");
        Habilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabilitarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ADMINISTRACION DE PRODUCTOS");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Clave producto:");

        estbox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        estbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estboxActionPerformed(evt);
            }
        });

        estadot.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        estadot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadot.setText("Estado:");

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Buscar2.setText("Realizar otra busqueda");
        Buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar2ActionPerformed(evt);
            }
        });

        cant.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cant.setText("Cantidad:");

        cantbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantboxKeyTyped(evt);
            }
        });

        claves.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(169, 169, 169))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clavebox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(claves, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombret)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombrebox, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(preciot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(preciobox, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cantbox, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(estadot)
                            .addGap(18, 18, 18)
                            .addComponent(estbox, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Buscar2)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(Habilitar)
                        .addGap(18, 18, 18)
                        .addComponent(Guardar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clavebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Buscar)
                    .addComponent(claves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cant))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombret)
                    .addComponent(nombrebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preciobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preciot))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadot))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Habilitar)
                    .addComponent(Guardar)
                    .addComponent(Eliminar))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Buscar2)
                    .addComponent(jButton2))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void precioboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioboxActionPerformed

    private void claveboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveboxActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
                
        int clave = Integer.parseInt(clavebox.getText().trim());
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/dulceria","root","");
            PreparedStatement select = cn.prepareStatement("select * from productos where clave = ?");
            
            select.setInt(1, clave);
            ResultSet rs = select.executeQuery();
            
            if(rs.next()){
                
                nombret.setVisible(true);
                nombrebox.setVisible(true); 
                preciot.setVisible(true);
                preciobox.setVisible(true); 
                estadot.setVisible(true);
                estbox.setVisible(true); 
                Habilitar.setVisible(true);
                cant.setVisible(true);
                cantbox.setVisible(true);
                clavebox.setEditable(false);
                Buscar.setVisible(false);
                
                cantbox.setText(rs.getString("cantidad"));
                nombrebox.setText(rs.getString("nombre"));
                preciobox.setText(rs.getString("precio"));
                
                boolean est = rs.getBoolean("estado"); 
                if(est == true)
                    estbox.setText("Esta a la venta");
                else
                    estbox.setText("No esta a la venta");
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Clave de producto no encontrada");
                clavebox.setText("");
            }
            
        }catch(Exception e ){
            System.err.print("Error: " + e);
        }
        
        Buscar2.setVisible(true);
    }//GEN-LAST:event_BuscarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        
        int clave = Integer.parseInt(clavebox.getText().trim());
        String nombre = nombrebox.getText().trim();
        float precio = Float.parseFloat(preciobox.getText().trim()); 
        String estado = estbox.getText().trim();
        int cantidad = Integer.parseInt(cantbox.getText().trim());
        
        pc.Editar(clave, cantidad, nombre, precio, estado);
        
        clavebox.setText("");clavebox.setEditable(true);
        cantbox.setText("");
        nombrebox.setText("");
        preciobox.setText("");
        estbox.setText("");
        
        Eliminar.setVisible(false);
        nombret.setVisible(false);
        nombrebox.setVisible(false); nombrebox.setEditable(false);
        preciot.setVisible(false);
        preciobox.setVisible(false); preciobox.setEditable(false);
        estadot.setVisible(false);
        estbox.setVisible(false); estbox.setEditable(false);
        Habilitar.setVisible(false);
        Guardar.setVisible(false);
        cant.setVisible(false);
        cantbox.setVisible(false);cantbox.setEditable(false);
       
        this.claves.setModel(pc.modeloproductos());
        Buscar.setVisible(true);
        
    }//GEN-LAST:event_GuardarActionPerformed

    private void HabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabilitarActionPerformed
        
        nombrebox.setEditable(true);
        preciobox.setEditable(true);
        estbox.setEditable(true);
        cantbox.setEditable(true);
        Guardar.setVisible(true);
        Buscar.setVisible(false);
        Habilitar.setVisible(false);
        Eliminar.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_HabilitarActionPerformed

    private void estboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrameMenu volver = new FrameMenu();
        volver.setVisible(true);
        this.setVisible(false);
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar2ActionPerformed
        
        Buscar.setVisible(true);
        clavebox.setText("");
        nombret.setVisible(false);
        nombrebox.setVisible(false); nombrebox.setEditable(false);
        preciot.setVisible(false);
        preciobox.setVisible(false); preciobox.setEditable(false);
        estadot.setVisible(false);
        estbox.setVisible(false); estbox.setEditable(false);
        cant.setVisible(false);
        cantbox.setVisible(false);cantbox.setEditable(false);
        Habilitar.setVisible(false);
        Guardar.setVisible(false);
        
        clavebox.setEditable(true);
        Buscar2.setVisible(false);
    }//GEN-LAST:event_Buscar2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AgregarProducto ir = new AgregarProducto();
        ir.setVisible(true);
        this.setVisible(false);      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        
        int clave = Integer.parseInt(clavebox.getText().trim());
        pc.Eliminar(clave);
        
        clavebox.setText("");
        clavebox.setEditable(true);
        Buscar.setVisible(true);
        
        nombret.setVisible(false);
        nombrebox.setVisible(false); nombrebox.setEditable(false);
        preciot.setVisible(false);
        preciobox.setVisible(false); preciobox.setEditable(false);
        estadot.setVisible(false);
        estbox.setVisible(false); estbox.setEditable(false);
        cant.setVisible(false);
        cantbox.setVisible(false);cantbox.setEditable(false);
        Habilitar.setVisible(false);
        Guardar.setVisible(false);
        Buscar2.setVisible(false);  
        
        this.claves.setModel(pc.modeloproductos());
    }//GEN-LAST:event_EliminarActionPerformed

    private void claveboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_claveboxKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane,"Solo se pueden ingresar valores numericos");
        }
    }//GEN-LAST:event_claveboxKeyTyped

    private void cantboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantboxKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane,"Solo se pueden ingresar valores numericos");
        }
    }//GEN-LAST:event_cantboxKeyTyped

    private void precioboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioboxKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane,"Solo se pueden ingresar valores numericos");
        }
    }//GEN-LAST:event_precioboxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Buscar2;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Habilitar;
    private javax.swing.JLabel cant;
    private javax.swing.JTextField cantbox;
    private javax.swing.JTextField clavebox;
    private javax.swing.JComboBox<String> claves;
    private javax.swing.JLabel estadot;
    private javax.swing.JTextField estbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nombrebox;
    private javax.swing.JLabel nombret;
    private javax.swing.JTextField preciobox;
    private javax.swing.JLabel preciot;
    // End of variables declaration//GEN-END:variables
}
